apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synapse.fullname" . }}-postgres
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.db.password }}
